#!/usr/bin/env php
<?php
/**
 * Hat tip:
 * @link https://github.com/laravel/installer/blob/master/laravel
 */
if (file_exists(__DIR__.'/../../autoload.php')) {
	require __DIR__.'/../../autoload.php';
} else {
	require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use Gimme\Commands\FilesCommand;

// Create Application
$application = new Application();

// Add Commands
$application->add(new FilesCommand());

// Run
$application->run();